name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
    
jobs:
  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.3.3
    with:
      working_directory: 'examples/complete/'

  nsg-with-flow-logs-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.3.3
    with:
      working_directory: 'examples/nsg_with_flow_logs/'

# Seperate Job for TFlint workflow call
  tf-lint:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-lint.yml@master
    secrets:
      GITHUB: ${{ secrets.GITHUB }}